# joint_state_controller:
#   type: joint_state_controller/JointStateController
#   publish_rate: 20
#   joint1_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: left_wheel_joint
#     pid: {p: 100.0, i: 0, d: 1.0}
#   joint2_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: right_wheel_joint
#     pid: {p: 100.0, i: 0, d: 1.0}



left_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: "left_wheel_joint"
  pid: {p: .10000, i: 0.055, d: 100}
right_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: "right_wheel_joint"
  pid: {p: 10000, i: 0.055, d: 100}

# mobile_base_controller:
#   type        : "diff_drive_controller/DiffDriveController"
#   left_wheel  : 'left_wheel_joint'
#   right_wheel : 'right_wheel_joint'
#   publish_rate: 100.0               # default: 50
#   pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
#   twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

#   # Wheel separation and diameter. These are both optional.
#   # diff_drive_controller will attempt to read either one or both from the
#   # URDF if not specified as a parameter
#   # wheel_separation : .4
#   # wheel_radius : 0.1

#   # Wheel separation and radius multipliers
#   wheel_separation_multiplier: 1.0 # default: 1.0
#   wheel_radius_multiplier    : 1.0 # default: 1.0

#   # Velocity commands timeout [s], default 0.5
#   cmd_vel_timeout: .25

#   # Base frame_id
#   base_frame_id: base_link #default: base_link
#   # velocity_rolling_window_size: 1000.0
#   publish_cmd: true
#   enable_odom_tf: true

#   # Velocity and acceleration limits
#   # Whenever a min_* is unspecified, default to -max_*
#   linear:
#     x:
#       has_velocity_limits    : true
#       max_velocity           : .50  # m/s
#       min_velocity           : -1.0 # m/s
#       has_acceleration_limits: true
#       max_acceleration       : 0.8  # m/s^2
#       min_acceleration       : -0.4 # m/s^2
#       has_jerk_limits        : true
#       max_jerk               : .50  # m/s^3
#   angular:
#     z:
#       has_velocity_limits    : true
#       max_velocity           : 1.7  # rad/s
#       has_acceleration_limits: true
#       max_acceleration       : 1.5  # rad/s^2
#       has_jerk_limits        : true
#       max_jerk               : .25  # rad/s^3