DWAPlannerROS:

# Robot Configuration Parameters

  acc_lim_x: 8.0
  acc_lim_y: 8.0
  acc_lim_th: 5.0
  max_vel_trans: 14.142135623730
  min_vel_trans: 0.0
  max_vel_x: 10.0
  min_vel_x: -10.0
  max_vel_y: 10.0
  min_vel_y: -10.0
  max_rot_ve: 17.0
  min_rot_vel: 0

# Goal Tolerance Parameters  

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

#Forward Simulation Parameters

  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 3
  vy_samples: 10
  vth_samples: 20
  controller_frequency: 100.0

#Trajectory Scoring Parameters

# The cost function used to score each trajectory is in the following form:
# cost =
#   path_distance_bias * (distance to path from the endpoint of the trajectory in meters)
#   + goal_distance_bias * (distance to local goal from the endpoint of the trajectory in meters)
#   + occdist_scale * (maximum obstacle cost along the trajectory in obstacle cost (0-254))

  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_cost_grid: false

#Oscillation Prevention Parameters

  oscillation_reset_dist: 0.05

#Global Plan Parameters

  prune_plan: true




